---
- name: Set up the primary pi
  hosts: pi-primary
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: true

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/trusted.gpg.d/docker.gpg
        mode: '0644'

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/debian bullseye stable
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: true
        state: started